#!/bin/bash
OPTIONS="Hello Date Name Quit"
select opt in $OPTIONS; do
	

	if [ "$opt" = "Hello" ]; then
	echo Hello dude!
	

	elif [ "$opt" = "Date" ]; then
	echo $(date)
	exit
	
	elif  [ "$opt" = "Name" ]; then
	echo "What is your name? "
	read name 
	echo "Hello $name"
	exit

	elif [ "$opt" = "Quit" ]; then
	echo Done..quitting.
	exit

	else
	echo Bad option
	fi
	break
	done

